package com.propmgr.dao;

// Generated Aug 2, 2015 5:17:33 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Actionmaster generated by hbm2java
 */
public class Actionmaster implements java.io.Serializable {

	private Long actionmasterid;
	private Pagemaster pagemaster;
	private String actionname;
	private Clob actiondescription;
	private Set actionroles = new HashSet(0);

	public Actionmaster() {
	}

	public Actionmaster(Pagemaster pagemaster, String actionname) {
		this.pagemaster = pagemaster;
		this.actionname = actionname;
	}

	public Actionmaster(Pagemaster pagemaster, String actionname,
			Clob actiondescription, Set actionroles) {
		this.pagemaster = pagemaster;
		this.actionname = actionname;
		this.actiondescription = actiondescription;
		this.actionroles = actionroles;
	}

	public Long getActionmasterid() {
		return this.actionmasterid;
	}

	public void setActionmasterid(Long actionmasterid) {
		this.actionmasterid = actionmasterid;
	}

	public Pagemaster getPagemaster() {
		return this.pagemaster;
	}

	public void setPagemaster(Pagemaster pagemaster) {
		this.pagemaster = pagemaster;
	}

	public String getActionname() {
		return this.actionname;
	}

	public void setActionname(String actionname) {
		this.actionname = actionname;
	}

	public Clob getActiondescription() {
		return this.actiondescription;
	}

	public void setActiondescription(Clob actiondescription) {
		this.actiondescription = actiondescription;
	}

	public Set getActionroles() {
		return this.actionroles;
	}

	public void setActionroles(Set actionroles) {
		this.actionroles = actionroles;
	}

}
