package com.propmgr.dao;

// Generated Jul 30, 2015 6:25:17 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Long addressid;
	private Statemaster statemaster;
	private Citymaster citymaster;
	private Clob addressline1;
	private Clob addressline2;
	private String zipcode;
	private Set projectbankaccounts = new HashSet(0);
	private Set customermasters = new HashSet(0);
	private Set usermasters = new HashSet(0);
	private Set organizations = new HashSet(0);
	private Set projectmasters = new HashSet(0);

	public Address() {
	}

	public Address(Statemaster statemaster, Citymaster citymaster) {
		this.statemaster = statemaster;
		this.citymaster = citymaster;
	}

	public Address(Statemaster statemaster, Citymaster citymaster,
			Clob addressline1, Clob addressline2, String zipcode,
			Set projectbankaccounts, Set customermasters, Set usermasters,
			Set organizations, Set projectmasters) {
		this.statemaster = statemaster;
		this.citymaster = citymaster;
		this.addressline1 = addressline1;
		this.addressline2 = addressline2;
		this.zipcode = zipcode;
		this.projectbankaccounts = projectbankaccounts;
		this.customermasters = customermasters;
		this.usermasters = usermasters;
		this.organizations = organizations;
		this.projectmasters = projectmasters;
	}

	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	public Statemaster getStatemaster() {
		return this.statemaster;
	}

	public void setStatemaster(Statemaster statemaster) {
		this.statemaster = statemaster;
	}

	public Citymaster getCitymaster() {
		return this.citymaster;
	}

	public void setCitymaster(Citymaster citymaster) {
		this.citymaster = citymaster;
	}

	public Clob getAddressline1() {
		return this.addressline1;
	}

	public void setAddressline1(Clob addressline1) {
		this.addressline1 = addressline1;
	}

	public Clob getAddressline2() {
		return this.addressline2;
	}

	public void setAddressline2(Clob addressline2) {
		this.addressline2 = addressline2;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Set getProjectbankaccounts() {
		return this.projectbankaccounts;
	}

	public void setProjectbankaccounts(Set projectbankaccounts) {
		this.projectbankaccounts = projectbankaccounts;
	}

	public Set getCustomermasters() {
		return this.customermasters;
	}

	public void setCustomermasters(Set customermasters) {
		this.customermasters = customermasters;
	}

	public Set getUsermasters() {
		return this.usermasters;
	}

	public void setUsermasters(Set usermasters) {
		this.usermasters = usermasters;
	}

	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

	public Set getProjectmasters() {
		return this.projectmasters;
	}

	public void setProjectmasters(Set projectmasters) {
		this.projectmasters = projectmasters;
	}

}
