package com.propmgr.dao;

// Generated Aug 3, 2015 11:44:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Amenity generated by hbm2java
 */
public class Amenity implements java.io.Serializable {

	private Long amenityid;
	private String amenitycode;
	private String amenitydescription;
	private Set unitamenities = new HashSet(0);
	private Set amenitypricepolicies = new HashSet(0);

	public Amenity() {
	}

	public Amenity(String amenitycode) {
		this.amenitycode = amenitycode;
	}

	public Amenity(String amenitycode, String amenitydescription,
			Set unitamenities, Set amenitypricepolicies) {
		this.amenitycode = amenitycode;
		this.amenitydescription = amenitydescription;
		this.unitamenities = unitamenities;
		this.amenitypricepolicies = amenitypricepolicies;
	}

	public Long getAmenityid() {
		return this.amenityid;
	}

	public void setAmenityid(Long amenityid) {
		this.amenityid = amenityid;
	}

	public String getAmenitycode() {
		return this.amenitycode;
	}

	public void setAmenitycode(String amenitycode) {
		this.amenitycode = amenitycode;
	}

	public String getAmenitydescription() {
		return this.amenitydescription;
	}

	public void setAmenitydescription(String amenitydescription) {
		this.amenitydescription = amenitydescription;
	}

	public Set getUnitamenities() {
		return this.unitamenities;
	}

	public void setUnitamenities(Set unitamenities) {
		this.unitamenities = unitamenities;
	}

	public Set getAmenitypricepolicies() {
		return this.amenitypricepolicies;
	}

	public void setAmenitypricepolicies(Set amenitypricepolicies) {
		this.amenitypricepolicies = amenitypricepolicies;
	}

}
