package com.propmgr.dao;

// Generated Oct 19, 2015 11:52:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Bankbranch generated by hbm2java
 */
public class Bankbranch implements java.io.Serializable {

	private Long bankbranchid;
	private Address address;
	private String bankname;
	private String branchname;
	private String ifsccode;
	private String micrcode;
	private Set projectbankaccounts = new HashSet(0);
	private Set refundmasters = new HashSet(0);
	private Set paymentmasters = new HashSet(0);

	public Bankbranch() {
	}

	public Bankbranch(Address address, String bankname, String branchname,
			String ifsccode, String micrcode) {
		this.address = address;
		this.bankname = bankname;
		this.branchname = branchname;
		this.ifsccode = ifsccode;
		this.micrcode = micrcode;
	}

	public Bankbranch(Address address, String bankname, String branchname,
			String ifsccode, String micrcode, Set projectbankaccounts,
			Set refundmasters, Set paymentmasters) {
		this.address = address;
		this.bankname = bankname;
		this.branchname = branchname;
		this.ifsccode = ifsccode;
		this.micrcode = micrcode;
		this.projectbankaccounts = projectbankaccounts;
		this.refundmasters = refundmasters;
		this.paymentmasters = paymentmasters;
	}

	public Long getBankbranchid() {
		return this.bankbranchid;
	}

	public void setBankbranchid(Long bankbranchid) {
		this.bankbranchid = bankbranchid;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	public String getBranchname() {
		return this.branchname;
	}

	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	public String getIfsccode() {
		return this.ifsccode;
	}

	public void setIfsccode(String ifsccode) {
		this.ifsccode = ifsccode;
	}

	public String getMicrcode() {
		return this.micrcode;
	}

	public void setMicrcode(String micrcode) {
		this.micrcode = micrcode;
	}

	public Set getProjectbankaccounts() {
		return this.projectbankaccounts;
	}

	public void setProjectbankaccounts(Set projectbankaccounts) {
		this.projectbankaccounts = projectbankaccounts;
	}

	public Set getRefundmasters() {
		return this.refundmasters;
	}

	public void setRefundmasters(Set refundmasters) {
		this.refundmasters = refundmasters;
	}

	public Set getPaymentmasters() {
		return this.paymentmasters;
	}

	public void setPaymentmasters(Set paymentmasters) {
		this.paymentmasters = paymentmasters;
	}

}
