package com.propmgr.dao;

// Generated Jun 23, 2015 11:52:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Citymaster generated by hbm2java
 */
public class Citymaster implements java.io.Serializable {

	private Long citymasterid;
	private String citycode;
	private String cityname;
	private Set addresses = new HashSet(0);

	public Citymaster() {
	}

	public Citymaster(String citycode, String cityname) {
		this.citycode = citycode;
		this.cityname = cityname;
	}

	public Citymaster(String citycode, String cityname, Set addresses) {
		this.citycode = citycode;
		this.cityname = cityname;
		this.addresses = addresses;
	}

	public Long getCitymasterid() {
		return this.citymasterid;
	}

	public void setCitymasterid(Long citymasterid) {
		this.citymasterid = citymasterid;
	}

	public String getCitycode() {
		return this.citycode;
	}

	public void setCitycode(String citycode) {
		this.citycode = citycode;
	}

	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
