package com.propmgr.dao;

// Generated Jul 18, 2015 11:02:19 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paymentmaster generated by hbm2java
 */
public class Paymentmaster implements java.io.Serializable {

	private Long paymentid;
	private Usermaster usermaster;
	private Unitbooking unitbooking;
	private Paymenttype paymenttype;
	private long receiptnumber;
	private Long altreceiptnumber;
	private double paymentamount;
	private Clob paymentdescription;
	private Date paymentreceiveddate;
	private String bankname;
	private String bankbranch;
	private String chequenumber;
	private Date chequedate;
	private String cardnumber;
	private String cardexpirydate;
	private String cardholdername;
	private String cardtype;
	private boolean editable;
	private String utrnumber;
	private Long project;
	private Set paymentstatuses = new HashSet(0);
	private Set paymentstages = new HashSet(0);

	public Paymentmaster() {
	}

	public Paymentmaster(Usermaster usermaster, Unitbooking unitbooking,
			Paymenttype paymenttype, long receiptnumber, double paymentamount,
			boolean editable) {
		this.usermaster = usermaster;
		this.unitbooking = unitbooking;
		this.paymenttype = paymenttype;
		this.receiptnumber = receiptnumber;
		this.paymentamount = paymentamount;
		this.editable = editable;
	}

	public Paymentmaster(Usermaster usermaster, Unitbooking unitbooking,
			Paymenttype paymenttype, long receiptnumber, Long altreceiptnumber,
			double paymentamount, Clob paymentdescription,
			Date paymentreceiveddate, String bankname, String bankbranch,
			String chequenumber, Date chequedate, String cardnumber,
			String cardexpirydate, String cardholdername, String cardtype,
			boolean editable, String utrnumber, Long project,
			Set paymentstatuses, Set paymentstages) {
		this.usermaster = usermaster;
		this.unitbooking = unitbooking;
		this.paymenttype = paymenttype;
		this.receiptnumber = receiptnumber;
		this.altreceiptnumber = altreceiptnumber;
		this.paymentamount = paymentamount;
		this.paymentdescription = paymentdescription;
		this.paymentreceiveddate = paymentreceiveddate;
		this.bankname = bankname;
		this.bankbranch = bankbranch;
		this.chequenumber = chequenumber;
		this.chequedate = chequedate;
		this.cardnumber = cardnumber;
		this.cardexpirydate = cardexpirydate;
		this.cardholdername = cardholdername;
		this.cardtype = cardtype;
		this.editable = editable;
		this.utrnumber = utrnumber;
		this.project = project;
		this.paymentstatuses = paymentstatuses;
		this.paymentstages = paymentstages;
	}

	public Long getPaymentid() {
		return this.paymentid;
	}

	public void setPaymentid(Long paymentid) {
		this.paymentid = paymentid;
	}

	public Usermaster getUsermaster() {
		return this.usermaster;
	}

	public void setUsermaster(Usermaster usermaster) {
		this.usermaster = usermaster;
	}

	public Unitbooking getUnitbooking() {
		return this.unitbooking;
	}

	public void setUnitbooking(Unitbooking unitbooking) {
		this.unitbooking = unitbooking;
	}

	public Paymenttype getPaymenttype() {
		return this.paymenttype;
	}

	public void setPaymenttype(Paymenttype paymenttype) {
		this.paymenttype = paymenttype;
	}

	public long getReceiptnumber() {
		return this.receiptnumber;
	}

	public void setReceiptnumber(long receiptnumber) {
		this.receiptnumber = receiptnumber;
	}

	public Long getAltreceiptnumber() {
		return this.altreceiptnumber;
	}

	public void setAltreceiptnumber(Long altreceiptnumber) {
		this.altreceiptnumber = altreceiptnumber;
	}

	public double getPaymentamount() {
		return this.paymentamount;
	}

	public void setPaymentamount(double paymentamount) {
		this.paymentamount = paymentamount;
	}

	public Clob getPaymentdescription() {
		return this.paymentdescription;
	}

	public void setPaymentdescription(Clob paymentdescription) {
		this.paymentdescription = paymentdescription;
	}

	public Date getPaymentreceiveddate() {
		return this.paymentreceiveddate;
	}

	public void setPaymentreceiveddate(Date paymentreceiveddate) {
		this.paymentreceiveddate = paymentreceiveddate;
	}

	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	public String getBankbranch() {
		return this.bankbranch;
	}

	public void setBankbranch(String bankbranch) {
		this.bankbranch = bankbranch;
	}

	public String getChequenumber() {
		return this.chequenumber;
	}

	public void setChequenumber(String chequenumber) {
		this.chequenumber = chequenumber;
	}

	public Date getChequedate() {
		return this.chequedate;
	}

	public void setChequedate(Date chequedate) {
		this.chequedate = chequedate;
	}

	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	public String getCardexpirydate() {
		return this.cardexpirydate;
	}

	public void setCardexpirydate(String cardexpirydate) {
		this.cardexpirydate = cardexpirydate;
	}

	public String getCardholdername() {
		return this.cardholdername;
	}

	public void setCardholdername(String cardholdername) {
		this.cardholdername = cardholdername;
	}

	public String getCardtype() {
		return this.cardtype;
	}

	public void setCardtype(String cardtype) {
		this.cardtype = cardtype;
	}

	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	public String getUtrnumber() {
		return this.utrnumber;
	}

	public void setUtrnumber(String utrnumber) {
		this.utrnumber = utrnumber;
	}

	public Long getProject() {
		return this.project;
	}

	public void setProject(Long project) {
		this.project = project;
	}

	public Set getPaymentstatuses() {
		return this.paymentstatuses;
	}

	public void setPaymentstatuses(Set paymentstatuses) {
		this.paymentstatuses = paymentstatuses;
	}

	public Set getPaymentstages() {
		return this.paymentstages;
	}

	public void setPaymentstages(Set paymentstages) {
		this.paymentstages = paymentstages;
	}

}
