package com.propmgr.dao;

// Generated Jul 18, 2015 11:02:19 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;

/**
 * Paymentstatus generated by hbm2java
 */
public class Paymentstatus implements java.io.Serializable {

	private Long paymentstatusid;
	private Paymentstate paymentstate;
	private Usermaster usermaster;
	private Paymentmaster paymentmaster;
	private Date statusdate;
	private Clob statuscomment;

	public Paymentstatus() {
	}

	public Paymentstatus(Paymentstate paymentstate, Usermaster usermaster,
			Paymentmaster paymentmaster, Date statusdate) {
		this.paymentstate = paymentstate;
		this.usermaster = usermaster;
		this.paymentmaster = paymentmaster;
		this.statusdate = statusdate;
	}

	public Paymentstatus(Paymentstate paymentstate, Usermaster usermaster,
			Paymentmaster paymentmaster, Date statusdate, Clob statuscomment) {
		this.paymentstate = paymentstate;
		this.usermaster = usermaster;
		this.paymentmaster = paymentmaster;
		this.statusdate = statusdate;
		this.statuscomment = statuscomment;
	}

	public Long getPaymentstatusid() {
		return this.paymentstatusid;
	}

	public void setPaymentstatusid(Long paymentstatusid) {
		this.paymentstatusid = paymentstatusid;
	}

	public Paymentstate getPaymentstate() {
		return this.paymentstate;
	}

	public void setPaymentstate(Paymentstate paymentstate) {
		this.paymentstate = paymentstate;
	}

	public Usermaster getUsermaster() {
		return this.usermaster;
	}

	public void setUsermaster(Usermaster usermaster) {
		this.usermaster = usermaster;
	}

	public Paymentmaster getPaymentmaster() {
		return this.paymentmaster;
	}

	public void setPaymentmaster(Paymentmaster paymentmaster) {
		this.paymentmaster = paymentmaster;
	}

	public Date getStatusdate() {
		return this.statusdate;
	}

	public void setStatusdate(Date statusdate) {
		this.statusdate = statusdate;
	}

	public Clob getStatuscomment() {
		return this.statuscomment;
	}

	public void setStatuscomment(Clob statuscomment) {
		this.statuscomment = statuscomment;
	}

}
