package com.propmgr.dao;

// Generated Aug 2, 2015 5:17:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * Paymentstage generated by hbm2java
 */
public class Paymentstage implements java.io.Serializable {

	private Long paymentstageid;
	private Paymentmaster paymentmaster;
	private int paymentstagetype;

	public Paymentstage() {
	}

	public Paymentstage(Paymentmaster paymentmaster, int paymentstagetype) {
		this.paymentmaster = paymentmaster;
		this.paymentstagetype = paymentstagetype;
	}

	public Long getPaymentstageid() {
		return this.paymentstageid;
	}

	public void setPaymentstageid(Long paymentstageid) {
		this.paymentstageid = paymentstageid;
	}

	public Paymentmaster getPaymentmaster() {
		return this.paymentmaster;
	}

	public void setPaymentmaster(Paymentmaster paymentmaster) {
		this.paymentmaster = paymentmaster;
	}

	public int getPaymentstagetype() {
		return this.paymentstagetype;
	}

	public void setPaymentstagetype(int paymentstagetype) {
		this.paymentstagetype = paymentstagetype;
	}

}
