package com.propmgr.dao;

// Generated Jul 1, 2015 11:15:39 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Long personid;
	private Contactinfo contactinfo;
	private String firstname;
	private String middlename;
	private String lastname;
	private Date dateofbirth;
	private String profession;
	private Clob otherdetail;
	private Set customermastersForCoownerdetail = new HashSet(0);
	private Set customermastersForPersondetail = new HashSet(0);
	private Set usermasters = new HashSet(0);
	private Set organizations = new HashSet(0);

	public Person() {
	}

	public Person(Contactinfo contactinfo, String firstname, String middlename,
			String lastname, Date dateofbirth, String profession,
			Clob otherdetail, Set customermastersForCoownerdetail,
			Set customermastersForPersondetail, Set usermasters,
			Set organizations) {
		this.contactinfo = contactinfo;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.dateofbirth = dateofbirth;
		this.profession = profession;
		this.otherdetail = otherdetail;
		this.customermastersForCoownerdetail = customermastersForCoownerdetail;
		this.customermastersForPersondetail = customermastersForPersondetail;
		this.usermasters = usermasters;
		this.organizations = organizations;
	}

	public Long getPersonid() {
		return this.personid;
	}

	public void setPersonid(Long personid) {
		this.personid = personid;
	}

	public Contactinfo getContactinfo() {
		return this.contactinfo;
	}

	public void setContactinfo(Contactinfo contactinfo) {
		this.contactinfo = contactinfo;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public Clob getOtherdetail() {
		return this.otherdetail;
	}

	public void setOtherdetail(Clob otherdetail) {
		this.otherdetail = otherdetail;
	}

	public Set getCustomermastersForCoownerdetail() {
		return this.customermastersForCoownerdetail;
	}

	public void setCustomermastersForCoownerdetail(
			Set customermastersForCoownerdetail) {
		this.customermastersForCoownerdetail = customermastersForCoownerdetail;
	}

	public Set getCustomermastersForPersondetail() {
		return this.customermastersForPersondetail;
	}

	public void setCustomermastersForPersondetail(
			Set customermastersForPersondetail) {
		this.customermastersForPersondetail = customermastersForPersondetail;
	}

	public Set getUsermasters() {
		return this.usermasters;
	}

	public void setUsermasters(Set usermasters) {
		this.usermasters = usermasters;
	}

	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

}
