package com.propmgr.dao;

// Generated Oct 19, 2015 11:52:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * Projectbankaccount generated by hbm2java
 */
public class Projectbankaccount implements java.io.Serializable {

	private Long projectbankaccountid;
	private Bankbranch bankbranch;
	private Bankaccounttype bankaccounttype;
	private Projectmaster projectmaster;
	private String accountnumber;
	private String accountholdername;

	public Projectbankaccount() {
	}

	public Projectbankaccount(Bankaccounttype bankaccounttype,
			Projectmaster projectmaster) {
		this.bankaccounttype = bankaccounttype;
		this.projectmaster = projectmaster;
	}

	public Projectbankaccount(Bankbranch bankbranch,
			Bankaccounttype bankaccounttype, Projectmaster projectmaster,
			String accountnumber, String accountholdername) {
		this.bankbranch = bankbranch;
		this.bankaccounttype = bankaccounttype;
		this.projectmaster = projectmaster;
		this.accountnumber = accountnumber;
		this.accountholdername = accountholdername;
	}

	public Long getProjectbankaccountid() {
		return this.projectbankaccountid;
	}

	public void setProjectbankaccountid(Long projectbankaccountid) {
		this.projectbankaccountid = projectbankaccountid;
	}

	public Bankbranch getBankbranch() {
		return this.bankbranch;
	}

	public void setBankbranch(Bankbranch bankbranch) {
		this.bankbranch = bankbranch;
	}

	public Bankaccounttype getBankaccounttype() {
		return this.bankaccounttype;
	}

	public void setBankaccounttype(Bankaccounttype bankaccounttype) {
		this.bankaccounttype = bankaccounttype;
	}

	public Projectmaster getProjectmaster() {
		return this.projectmaster;
	}

	public void setProjectmaster(Projectmaster projectmaster) {
		this.projectmaster = projectmaster;
	}

	public String getAccountnumber() {
		return this.accountnumber;
	}

	public void setAccountnumber(String accountnumber) {
		this.accountnumber = accountnumber;
	}

	public String getAccountholdername() {
		return this.accountholdername;
	}

	public void setAccountholdername(String accountholdername) {
		this.accountholdername = accountholdername;
	}

}
