package com.propmgr.dao;

// Generated Aug 2, 2015 5:17:33 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Projectmaster generated by hbm2java
 */
public class Projectmaster implements java.io.Serializable {

	private Long projectid;
	private Address address;
	private Organization organization;
	private String projectname;
	private Clob projectdescription;
	private long totalphases;
	private Clob termsandconditions;
	private String logofilename;
	private Set projectbankaccounts = new HashSet(0);
	private Set projectphases = new HashSet(0);

	public Projectmaster() {
	}

	public Projectmaster(Address address, Organization organization,
			String projectname, long totalphases) {
		this.address = address;
		this.organization = organization;
		this.projectname = projectname;
		this.totalphases = totalphases;
	}

	public Projectmaster(Address address, Organization organization,
			String projectname, Clob projectdescription, long totalphases,
			Clob termsandconditions, String logofilename,
			Set projectbankaccounts, Set projectphases) {
		this.address = address;
		this.organization = organization;
		this.projectname = projectname;
		this.projectdescription = projectdescription;
		this.totalphases = totalphases;
		this.termsandconditions = termsandconditions;
		this.logofilename = logofilename;
		this.projectbankaccounts = projectbankaccounts;
		this.projectphases = projectphases;
	}

	public Long getProjectid() {
		return this.projectid;
	}

	public void setProjectid(Long projectid) {
		this.projectid = projectid;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	public Clob getProjectdescription() {
		return this.projectdescription;
	}

	public void setProjectdescription(Clob projectdescription) {
		this.projectdescription = projectdescription;
	}

	public long getTotalphases() {
		return this.totalphases;
	}

	public void setTotalphases(long totalphases) {
		this.totalphases = totalphases;
	}

	public Clob getTermsandconditions() {
		return this.termsandconditions;
	}

	public void setTermsandconditions(Clob termsandconditions) {
		this.termsandconditions = termsandconditions;
	}

	public String getLogofilename() {
		return this.logofilename;
	}

	public void setLogofilename(String logofilename) {
		this.logofilename = logofilename;
	}

	public Set getProjectbankaccounts() {
		return this.projectbankaccounts;
	}

	public void setProjectbankaccounts(Set projectbankaccounts) {
		this.projectbankaccounts = projectbankaccounts;
	}

	public Set getProjectphases() {
		return this.projectphases;
	}

	public void setProjectphases(Set projectphases) {
		this.projectphases = projectphases;
	}

}
