package com.propmgr.dao;

// Generated Oct 19, 2015 11:52:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Refundmaster generated by hbm2java
 */
public class Refundmaster implements java.io.Serializable {

	private Long refundmasterid;
	private Unitbooking unitbooking;
	private Bankbranch bankbranch;
	private Double refundamount;
	private Date refunddate;
	private String chequenumber;
	private Date chequedate;

	public Refundmaster() {
	}

	public Refundmaster(Unitbooking unitbooking) {
		this.unitbooking = unitbooking;
	}

	public Refundmaster(Unitbooking unitbooking, Bankbranch bankbranch,
			Double refundamount, Date refunddate, String chequenumber,
			Date chequedate) {
		this.unitbooking = unitbooking;
		this.bankbranch = bankbranch;
		this.refundamount = refundamount;
		this.refunddate = refunddate;
		this.chequenumber = chequenumber;
		this.chequedate = chequedate;
	}

	public Long getRefundmasterid() {
		return this.refundmasterid;
	}

	public void setRefundmasterid(Long refundmasterid) {
		this.refundmasterid = refundmasterid;
	}

	public Unitbooking getUnitbooking() {
		return this.unitbooking;
	}

	public void setUnitbooking(Unitbooking unitbooking) {
		this.unitbooking = unitbooking;
	}

	public Bankbranch getBankbranch() {
		return this.bankbranch;
	}

	public void setBankbranch(Bankbranch bankbranch) {
		this.bankbranch = bankbranch;
	}

	public Double getRefundamount() {
		return this.refundamount;
	}

	public void setRefundamount(Double refundamount) {
		this.refundamount = refundamount;
	}

	public Date getRefunddate() {
		return this.refunddate;
	}

	public void setRefunddate(Date refunddate) {
		this.refunddate = refunddate;
	}

	public String getChequenumber() {
		return this.chequenumber;
	}

	public void setChequenumber(String chequenumber) {
		this.chequenumber = chequenumber;
	}

	public Date getChequedate() {
		return this.chequedate;
	}

	public void setChequedate(Date chequedate) {
		this.chequedate = chequedate;
	}

}
