package com.propmgr.dao;

// Generated Jul 28, 2015 11:20:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sourcemaster generated by hbm2java
 */
public class Sourcemaster implements java.io.Serializable {

	private Long sourcemasterid;
	private String sourcecode;
	private String sourcename;
	private Set enquiries = new HashSet(0);

	public Sourcemaster() {
	}

	public Sourcemaster(String sourcecode, String sourcename, Set enquiries) {
		this.sourcecode = sourcecode;
		this.sourcename = sourcename;
		this.enquiries = enquiries;
	}

	public Long getSourcemasterid() {
		return this.sourcemasterid;
	}

	public void setSourcemasterid(Long sourcemasterid) {
		this.sourcemasterid = sourcemasterid;
	}

	public String getSourcecode() {
		return this.sourcecode;
	}

	public void setSourcecode(String sourcecode) {
		this.sourcecode = sourcecode;
	}

	public String getSourcename() {
		return this.sourcename;
	}

	public void setSourcename(String sourcename) {
		this.sourcename = sourcename;
	}

	public Set getEnquiries() {
		return this.enquiries;
	}

	public void setEnquiries(Set enquiries) {
		this.enquiries = enquiries;
	}

}
