package com.propmgr.dao;

// Generated Jul 18, 2015 11:02:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Statemaster generated by hbm2java
 */
public class Statemaster implements java.io.Serializable {

	private Long statemasterid;
	private String statecode;
	private String statename;
	private Set addresses = new HashSet(0);

	public Statemaster() {
	}

	public Statemaster(String statecode, String statename, Set addresses) {
		this.statecode = statecode;
		this.statename = statename;
		this.addresses = addresses;
	}

	public Long getStatemasterid() {
		return this.statemasterid;
	}

	public void setStatemasterid(Long statemasterid) {
		this.statemasterid = statemasterid;
	}

	public String getStatecode() {
		return this.statecode;
	}

	public void setStatecode(String statecode) {
		this.statecode = statecode;
	}

	public String getStatename() {
		return this.statename;
	}

	public void setStatename(String statename) {
		this.statename = statename;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
