package com.propmgr.dao;

// Generated Aug 2, 2015 5:17:33 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;

/**
 * Unitpaymentschedule generated by hbm2java
 */
public class Unitpaymentschedule implements java.io.Serializable {

	private Long unitpaymentscheduleid;
	private Projectbuilding projectbuilding;
	private int paymentscheduleposition;
	private String paymentscheduletype;
	private Clob paymentscheduledescription;
	private Double percentamount;
	private Date paymentscheduledate;
	private int applicableto;

	public Unitpaymentschedule() {
	}

	public Unitpaymentschedule(Projectbuilding projectbuilding,
			int paymentscheduleposition, String paymentscheduletype,
			int applicableto) {
		this.projectbuilding = projectbuilding;
		this.paymentscheduleposition = paymentscheduleposition;
		this.paymentscheduletype = paymentscheduletype;
		this.applicableto = applicableto;
	}

	public Unitpaymentschedule(Projectbuilding projectbuilding,
			int paymentscheduleposition, String paymentscheduletype,
			Clob paymentscheduledescription, Double percentamount,
			Date paymentscheduledate, int applicableto) {
		this.projectbuilding = projectbuilding;
		this.paymentscheduleposition = paymentscheduleposition;
		this.paymentscheduletype = paymentscheduletype;
		this.paymentscheduledescription = paymentscheduledescription;
		this.percentamount = percentamount;
		this.paymentscheduledate = paymentscheduledate;
		this.applicableto = applicableto;
	}

	public Long getUnitpaymentscheduleid() {
		return this.unitpaymentscheduleid;
	}

	public void setUnitpaymentscheduleid(Long unitpaymentscheduleid) {
		this.unitpaymentscheduleid = unitpaymentscheduleid;
	}

	public Projectbuilding getProjectbuilding() {
		return this.projectbuilding;
	}

	public void setProjectbuilding(Projectbuilding projectbuilding) {
		this.projectbuilding = projectbuilding;
	}

	public int getPaymentscheduleposition() {
		return this.paymentscheduleposition;
	}

	public void setPaymentscheduleposition(int paymentscheduleposition) {
		this.paymentscheduleposition = paymentscheduleposition;
	}

	public String getPaymentscheduletype() {
		return this.paymentscheduletype;
	}

	public void setPaymentscheduletype(String paymentscheduletype) {
		this.paymentscheduletype = paymentscheduletype;
	}

	public Clob getPaymentscheduledescription() {
		return this.paymentscheduledescription;
	}

	public void setPaymentscheduledescription(Clob paymentscheduledescription) {
		this.paymentscheduledescription = paymentscheduledescription;
	}

	public Double getPercentamount() {
		return this.percentamount;
	}

	public void setPercentamount(Double percentamount) {
		this.percentamount = percentamount;
	}

	public Date getPaymentscheduledate() {
		return this.paymentscheduledate;
	}

	public void setPaymentscheduledate(Date paymentscheduledate) {
		this.paymentscheduledate = paymentscheduledate;
	}

	public int getApplicableto() {
		return this.applicableto;
	}

	public void setApplicableto(int applicableto) {
		this.applicableto = applicableto;
	}

}
