package com.propmgr.dao;

// Generated Jun 23, 2015 11:52:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Unitmodificationstate generated by hbm2java
 */
public class Unitmodificationstate implements java.io.Serializable {

	private Long unitmodificationstateid;
	private String unitmodificationstatename;
	private Set unitmodificationstatuses = new HashSet(0);

	public Unitmodificationstate() {
	}

	public Unitmodificationstate(String unitmodificationstatename) {
		this.unitmodificationstatename = unitmodificationstatename;
	}

	public Unitmodificationstate(String unitmodificationstatename,
			Set unitmodificationstatuses) {
		this.unitmodificationstatename = unitmodificationstatename;
		this.unitmodificationstatuses = unitmodificationstatuses;
	}

	public Long getUnitmodificationstateid() {
		return this.unitmodificationstateid;
	}

	public void setUnitmodificationstateid(Long unitmodificationstateid) {
		this.unitmodificationstateid = unitmodificationstateid;
	}

	public String getUnitmodificationstatename() {
		return this.unitmodificationstatename;
	}

	public void setUnitmodificationstatename(String unitmodificationstatename) {
		this.unitmodificationstatename = unitmodificationstatename;
	}

	public Set getUnitmodificationstatuses() {
		return this.unitmodificationstatuses;
	}

	public void setUnitmodificationstatuses(Set unitmodificationstatuses) {
		this.unitmodificationstatuses = unitmodificationstatuses;
	}

}
