package com.propmgr.dao;

// Generated Jun 23, 2015 11:52:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Unittype generated by hbm2java
 */
public class Unittype implements java.io.Serializable {

	private Long unittypeid;
	private String unittypecode;
	private String unittypename;
	private Set unitmasters = new HashSet(0);
	private Set enquiries = new HashSet(0);

	public Unittype() {
	}

	public Unittype(String unittypecode, String unittypename, Set unitmasters,
			Set enquiries) {
		this.unittypecode = unittypecode;
		this.unittypename = unittypename;
		this.unitmasters = unitmasters;
		this.enquiries = enquiries;
	}

	public Long getUnittypeid() {
		return this.unittypeid;
	}

	public void setUnittypeid(Long unittypeid) {
		this.unittypeid = unittypeid;
	}

	public String getUnittypecode() {
		return this.unittypecode;
	}

	public void setUnittypecode(String unittypecode) {
		this.unittypecode = unittypecode;
	}

	public String getUnittypename() {
		return this.unittypename;
	}

	public void setUnittypename(String unittypename) {
		this.unittypename = unittypename;
	}

	public Set getUnitmasters() {
		return this.unitmasters;
	}

	public void setUnitmasters(Set unitmasters) {
		this.unitmasters = unitmasters;
	}

	public Set getEnquiries() {
		return this.enquiries;
	}

	public void setEnquiries(Set enquiries) {
		this.enquiries = enquiries;
	}

}
